title: Jacob Zamora # your name (or website title) here
logo: "https://media.licdn.com/dms/image/C4E03AQFxxT9cFLYNvQ/profile-displayphoto-shrink_800_800/0/1641230696863?e=1676505600&v=beta&t=Kp1tzqSzeyhG4dLY1y7MCkOn8ZaCvdE2jbWLGoBAomU" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
